### ISSUE TITLE
Cannot run 

### ISSUE THREAD

**Issue by divanvisagie** [twitter/finatra-activator-thrift-seed#1]
running `sbt run` on a fresh project generated with this causes `[error] (root/compile:backgroundRun) No main class detected.`

Possibly related to https://github.com/twitter/finatra/issues/315

**Comment by divanvisagie** [comment]
Forgive my noobness with sbt
As mentioned in twitter/finatra#315 

``` sh
sbt
> project server
> project run
```

I think it would be nice to have it as a default though

**Comment by cacoco** [comment]
@divanvisagie you can do: `sbt server/run`. 

See the sbt [documentation for multi-module](http://www.scala-sbt.org/0.13/docs/Multi-Project.html) projects.

**Comment by divanvisagie** [comment]
Hi , excuse the ignorance. Just started using Scala and sbt recently. Would you mind if I forked and added a little bit about getting things up and running to your README?

**Comment by cacoco** [comment]
@divanvisagie no worries. Unfortunately a bit of familiarity with sbt is required since this is a multi-module project. Feel free to put up a pull request and we'll review it. Thanks!
